apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t8a0v6myo-nodejs
  janus-idp.io/tekton: t8a0v6myo-nodejs
  backstage.io/kubernetes-id: t8a0v6myo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t8a0v6myo-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
